### ISSUE TITLE
How to adjust Savings graph?

### ISSUE THREAD

**Issue by jgleigh** [jasonacox/Powerwall-Dashboard#18]
What's the best way to change the settings for cost savings? I buy energy at ~$0.12 and sell it back at ~$0.05.

**Comment by jasonacox** [comment]
HI @jgleigh  - you can edit the panel - click on the header to "Savings" and the dropdown has "Edit".

<img width="283" alt="Screen Shot 2022-04-08 at 7 26 47 PM" src="https://user-images.githubusercontent.com/836718/162553172-5f75aaed-9e26-42a8-997d-a9a7c9278ebe.png">

There are four queries below that have `0.19` (representing $0.19/kWh) - change all of them to `0.12` except for the ones that show `sum("to_grid") * 0.19` and instead, make those `0.05`.

<img width="729" alt="image" src="https://user-images.githubusercontent.com/836718/162553378-0e5fea34-900e-4b7d-9ce6-c83ed78fea22.png">

After you finish the edit, save the dashboard by using the "save" icon at the top.

<img width="157" alt="image" src="https://user-images.githubusercontent.com/836718/162553330-11cba1d8-c429-4754-a94d-30f4280d67e5.png">

**Comment by jgleigh** [comment]
Excellent, thanks!

**Comment by jasonacox** [comment]
Hi @jgleigh - There is one error in my instruction to you.  You should adjust the "to_grid" for the "B" query (the "Solar" savings = cost avoidance of powering the house by solar only) to be the same rate as the "from_grid":  `sum("to_grid") * 0.12`.  This is because it is not computing the revenue you are getting by selling back to the grid but subtracting out the represented power that is not going to the house.  Only "C" query should be changed to the `0.05` value.

<img width="650" alt="image" src="https://user-images.githubusercontent.com/836718/162588233-9173f9e0-ed79-43ae-83ec-b09bc151e1dc.png">

Sorry for the confusion - I'll edit my instructions above for anyone else finding this.

**Comment by jgleigh** [comment]
I realized it's a little more complicated because that same calculation gets used in D. I ended up just putting them all at $0.11 which is close enough for rough numbers.

**Comment by jasonacox** [comment]
Great catch @jgleigh !   The "D" query would need to be updated to have both (one at 0.12 for subtraction and one at 0.05 for revenue).  I created `tgg` for the 0.05 value:

SELECT tgg + (s - tp - tg ) + fp FROM (SELECT sum("to_pw")  * 0.12 AS tp, sum("solar") * 0.12 AS s, sum("to_grid") * 0.05 AS tgg, sum("to_grid") * 0.12 AS tg, sum("from_pw") * 0.12 AS fp FROM kwh.http WHERE  $timeFilter tz('America/Los_Angeles'))

**Comment by jgleigh** [comment]
Thanks
