### ISSUE TITLE
Set Grafana option to allow embedding in web page.

### ISSUE THREAD

**Issue by dkerr64** [jasonacox/Powerwall-Dashboard#219]
I want to embed grafana into my own web page but it is blocked because Grafana sets  'X-Frame-Options' to 'deny'.

However this can be enabled by setting `allow_embedding=true` documented [here](https://grafana.com/docs/grafana/latest/setup-grafana/configure-grafana/#allow_embedding). Can we have that added to the Grafana server please?  Either as an option or fixed.

Thanks
David

**Comment by jasonacox** [comment]
Hi David, nice find! It looks like this can be fixed by adding this to your `grafana.env` file:

```
GF_SECURITY_ALLOW_EMBEDDING=true
```

The setup.sh script copies the `grafana.env.sample` file to `grafana.env` to allow for customization no impacted by `upgrade.sh`.  You should be able to add that additional line and recreate grafana container with `./compose-dash.sh up -d`

I do think this would be a good default.  I'll tag this as an enhancement.  However, it will only show up in new installs.  Existing dashboard users will need to manually add it to their `grafana.env` file.
