### ISSUE TITLE
Powerwall temp set to Celsius ignoring config

### ISSUE THREAD

**Issue by VenomrushCT** [jasonacox/Powerwall-Dashboard#229]
Despite config is set in Imperial, the Powerwall temp on the default Dashboard is always in Celsius.

**Comment by jasonacox** [comment]
Hi @VenomrushCT - thanks for opening this.  The metric/imperial config is only related to the weather data. The Powerwall temp data is only available in Celsius.  I'll add a note to update the setup so that it is clear that it is only for weather data.  

However, there is a way to have Grafana convert the Powerwall temp data to Fahrenheit:

<img width="783" alt="image" src="https://user-images.githubusercontent.com/836718/229019233-797ac1f3-d847-4671-a289-0fab2d671cda.png">

**Comment by VenomrushCT** [comment]
Thanks!

Added math(* 1.8 + 32) and changed Y axis label.
