### ISSUE TITLE
Savings Chart

### ISSUE THREAD

**Issue by cwagz** [jasonacox/Powerwall-Dashboard#6]
Maybe just a misunderstanding on my part, but I am not understanding how this chart works:

<img width="284" alt="image" src="https://user-images.githubusercontent.com/13752647/154860531-8f4b5698-0dc6-4a47-9e92-e043138d2b43.png">

Does this use the TOU rates that I have loaded in the Tesla app? Why does the combined value exceed the sum of solar and battery?

**Comment by jasonacox** [comment]
Unfortunately there is no connection to the Tesla app settings to get the TOU data.  The Savings Chart was inherited from the powerwall_montior project.  It was always on my list to fix this so I worked on it tonight.  I have a new version that I hope makes a lot more sense.  However, it doesn't factor in TOU. It just assume $0.19/kWh which you can edit.  Because there are so many TOU plans, I figure I will start with the lowest common savings, but at least break it down in a way that makes more sense:

<img width="223" alt="image" src="https://user-images.githubusercontent.com/836718/154897256-3b37c5a9-4b43-49b2-824d-138626286276.png">

Future to-do:  Create a stacked TOU graph.  If you figure it out, please feel free to share. :-)
